runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: pycrypto
  version: 2.6
- name: ssl
  version: 2.7.11

default_expiration: "1s"

handlers:
# The endpoints handler must be mapped to /_ah/api.
- url: /_ah/api/.*
  script: main.api
- url: /static
  static_dir: static
- url: /
  static_files: templates/index.html
  upload: templates/index.html
- url: /transactions
  static_files: templates/transactions.html
  upload: templates/transactions.html
- url: /.*
  script: main.app